version: "3"
services:
  app:
    build: .
    command: test
    environment:
      WRI_API_URL: https://api.resourcewatch.org/v1
    ports:
      - "3000:3000"
    restart: always
    container_name: resource-watch
    depends_on:
      - redis

  redis:
    image: redis
