apiVersion: v1
kind: Service
metadata:
  namespace: rw
  labels:
    name: {name}-mapbox
  name: {name}-mapbox
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    name: {name}-mapbox
