name: Run tests for the base branch

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        node-version: [14.15.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      WRI_API_URL: https://staging-api.globalforestwatch.org/v1
      PORT: 3000
      RW_NODE_ENV: development
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      SECRET: keyboard cat
      STATIC_SERVER_URL:
      API_ENV: production,preproduction
      CALLBACK_URL: http://localhost:3000/auth
      APPLICATIONS: rw
      CONTROL_TOWER_URL: https://staging-api.globalforestwatch.org
      BLOG_API_URL: https://blog.resourcewatch.org/wp-json/wp/v2
      BASEMAP_TILE_URL: https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png
      TRANSIFEX_LIVE_API: abcdef1234567890abcdef1234567890
      GOOGLE_ANALYTICS: UA-12345678-9
      PARDOT_NEWSLETTER_URL: https://go.pardot.com/l/123456/2020-02-02/3ab4cd
      ADD_SEARCH_KEY: abcdef1234567890abcdef1234567890
      RW_GOGGLE_API_TOKEN_SHORTENER: fakeBingToken
      BING_MAPS_API_KEY: fakeBingToken
      LOGGER_LEVEL: info
      RW_MAPBOX_API_TOKEN: fakeMapboxToken
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          - run: yarn install
          - run: yarn build
          - run: yarn start
          - run: yarn test


#      - name: Run tests using docker-compose
#        run: ./resourcewatch.sh test
