name: Run tests for the base branch

on:
  pull_request:
  push:
    branches:
      - master
      - preproduction
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        node: [ '14.17' ]

    env:
      CC_TEST_REPORTER_ID: 1a3b4790c97b84d93856c16cd0ceac7070a43c7620444d9de945c75c2edfa676
      CYPRESS_BASE_URL: http://localhost:3000
      FAIL_FAST_ENABLED: false
      LOGGER_LEVEL: info
      NEXTAUTH_URL: http://localhost:3000
      NEXT_PUBLIC_API_ENV: production
      NEXT_PUBLIC_APPLICATIONS: rw
      NEXT_PUBLIC_BLOG_API_URL: https://blog.resourcewatch.org/wp-json/wp/v2
      NEXT_PUBLIC_AUTH_CALLBACK: http://localhost:3000/auth-callback
      NEXT_PUBLIC_RW_ENV: test
      NEXT_PUBLIC_RW_GOGGLE_API_TOKEN_SHORTENER: fakeGoogleApiToken
      NEXT_PUBLIC_RW_MAPBOX_API_TOKEN: fakeMapboxToken
      NEXT_PUBLIC_ADD_SEARCH_KEY: abcdef1234567890abcdef1234567890
      NEXT_PUBLIC_BITLY_TOKEN: fakeBitlyToken
      NEXT_PUBLIC_WRI_API_URL: https://api.resourcewatch.org
      # NODE_ENV: test
      # NODE_OPTIONS: "--max-old-space-size=8192"
      PORT: 3000
      REDIS_URL: redis://localhost:6379
      SECRET: keyboard cat
      TEST_ENV: FRONTEND

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:test

#      - name: Start server
#        run: yarn start &

      - name: Run tests with coverage
        uses: paambaati/codeclimate-action@v2.7.5
        with:
          coverageCommand: yarn cover
